language: ruby
env: DEBUG=true
rvm:
  - 2.3.0
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - ruby-head
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - jruby-9000   # JRuby 9.0.0.0!
before_install:
  - gem install bundler
